/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "SENTRY_AUTH_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TURSO_AUTH_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TURSO_DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
