export const players_2024 = [
  {
    name: "Betriebsstättenleiter Sören",
    emoji: "🧢",
    priority: 5,
    status: "ACTIVE",
  },
  {
    name: "Yannick",
    emoji: "🤤",
    priority: 10,
    status: "ACTIVE",
  },
  {
    name: "Ansgar",
    emoji: "🥔",
    priority: 20,
    status: "ACTIVE",
  },
  {
    name: "Paul",
    emoji: "🐼",
    priority: 40,
    status: "ACTIVE",
  },
  {
    name: "Gimbledore",
    emoji: "✨",
    priority: 50,
    status: "ACTIVE",
  },
  {
    name: "Tristan die Schorle",
    emoji: "🥂",
    priority: 60,
    status: "ACTIVE",
  },
  {
    name: "Fabian",
    emoji: "🍆",
    priority: 70,
    status: "ACTIVE",
  },
  {
    name: "Jakob",
    emoji: "🥸",
    priority: 80,
    status: "ACTIVE",
  },
  {
    name: "Basti",
    emoji: "🏇🏻",
    priority: 90,
    status: "ACTIVE",
  },
  {
    name: "Felix",
    emoji: "😤",
    priority: 100,
    status: "ACTIVE",
  },
  {
    name: "Zernickel",
    emoji: "🇰🇿",
    priority: 110,
    status: "ACTIVE",
  },
  {
    name: "Marvin",
    emoji: "🦖",
    priority: 120,
    status: "ACTIVE",
  },
  {
    name: "Joel",
    emoji: "💾",
    priority: 130,
    status: "ACTIVE",
  },
  {
    name: "Tilman",
    emoji: "🕶️",
    priority: 140,
    status: "ACTIVE",
  },
  {
    name: "Neef",
    emoji: "🏓",
    priority: 150,
    status: "ACTIVE",
  },
  {
    name: "Robert",
    emoji: "🦄",
    priority: 160,
    status: "ACTIVE",
  },
  {
    name: "Alexandro",
    emoji: "🤌",
    priority: 170,
    status: "ACTIVE",
  },
  {
    name: "Katja",
    emoji: "🌺",
    priority: 180,
    status: "ACTIVE",
  },
  {
    name: "Leo",
    emoji: "🎣",
    priority: 190,
    status: "ACTIVE",
  },
  {
    name: "Miro",
    emoji: "🚜",
    priority: 200,
    status: "ACTIVE",
  },
  {
    name: "Anna",
    emoji: "🏎️",
    priority: 210,
    status: "ACTIVE",
  },
  {
    name: "Lohrey",
    emoji: "🏸",
    priority: 220,
    status: "ACTIVE",
  },
  {
    name: "Patzner",
    emoji: "🛫",
    priority: 230,
    status: "ACTIVE",
  },
  {
    name: "Jonas",
    emoji: "🧑‍🦲",
    priority: 240,
    status: "ACTIVE",
  },
  {
    name: "Michi",
    emoji: "♿︎",
    priority: 250,
    status: "ACTIVE",
  },
  {
    name: "Nico",
    emoji: "🇹🇭",
    priority: 260,
    status: "ACTIVE",
  },
  {
    name: "Flo",
    emoji: "⛷️",
    priority: 270,
    status: "ACTIVE",
  },
  {
    name: "Kevin",
    emoji: "🏗️",
    priority: 500,
    status: "INACTIVE",
  },
  {
    name: "Anna",
    emoji: "🥶",
    priority: 530,
    status: "ACTIVE",
  },
  {
    name: "Bilal",
    emoji: "🐵",
    priority: 540,
    status: "INACTIVE",
  },
  {
    name: "Shao",
    emoji: "🎥",
    priority: 3000,
    status: "INACTIVE",
  },
  {
    name: "Nebojsa",
    emoji: "🐻",
    priority: 3000,
    status: "INACTIVE",
  },
  {
    name: "Moritz",
    emoji: "🪰",
    priority: 3000,
    status: "INACTIVE",
  },
  {
    name: "Dennis",
    emoji: "🦘",
    priority: 3000,
    status: "INACTIVE",
  },
  {
    name: "Bastian",
    emoji: "🥵",
    priority: 5000,
    status: "ACTIVE",
  },
  {
    name: "Maddin",
    emoji: "🐘",
    priority: 5000,
    status: "ACTIVE",
  },
  {
    name: "Tomothy",
    emoji: "🎹",
    priority: 5000,
    status: "ACTIVE",
  },
  {
    name: "Waseem",
    emoji: "😛",
    priority: 7000,
    status: "INACTIVE",
  },
  {
    name: "Louis",
    emoji: "🤾‍♂️",
    priority: 7000,
    status: "INACTIVE",
  },
  {
    name: "Aaron",
    emoji: "🧑🏻‍🦲",
    priority: 9000,
    status: "HALL_OF_FAME",
  },
  {
    name: "Kian",
    emoji: "☕️",
    priority: 9999,
    status: "INACTIVE",
  },
  {
    name: "Marco",
    emoji: "😴",
    priority: 9999,
    status: "INACTIVE",
  },
  {
    name: "Christoph",
    emoji: "👨‍🍳",
    priority: 9999,
    status: "INACTIVE",
  },
  {
    name: "Thomas",
    emoji: "👽",
    priority: 9999,
    status: "INACTIVE",
  },
  {
    name: "Kristoffer",
    emoji: "🏓",
    priority: 9999,
    status: "ACTIVE",
  },
  {
    name: "Oggy",
    emoji: "🔥",
    priority: 9999,
    status: "ACTIVE",
  },
  {
    name: "Manish",
    emoji: "👳‍♂️",
    priority: 9999,
    status: "ACTIVE",
  },
  {
    name: "Christian K.",
    emoji: "💥",
    priority: 9999,
    status: "ACTIVE",
  },
  {
    name: "Marcel",
    emoji: "😇",
    priority: 9999,
    status: "INACTIVE",
  },
  {
    name: "Matze",
    emoji: "🏀",
    priority: 9999,
    status: "INACTIVE",
  },
  {
    name: "Daniel Gemündt",
    emoji: "🐼",
    priority: 9999,
    status: "ACTIVE",
  },
  {
    name: "Kris",
    emoji: "🐼",
    priority: 9999,
    status: "ACTIVE",
  },
  {
    name: "tHoMaS",
    emoji: "🏴",
    priority: 9999,
    status: "ACTIVE",
  },
  {
    name: "Stanley",
    emoji: "🫡",
    priority: 9999,
    status: "ACTIVE",
  },
  {
    name: "Linus",
    emoji: "👽",
    priority: 9999,
    status: "ACTIVE",
  },
  {
    name: "Lukas",
    emoji: "😬",
    priority: 9999,
    status: "ACTIVE",
  },
] as const;
